version: '3.6'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_users
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_PASSWORD:12345
    volumes:
      - mongo:/data/db

volumes:
  mongo: